### Файлы: CSV-формат [Домашнее задание]

Загрузите на свой ПК CSV-файл «Annual enterprise survey: 2018 financial year (provisional) – CSV» по следующей ссылке: https://www.stats.govt.nz/large-datasets/csv-files-for-download/

In [2]:
import csv
rows = [['Mike','Alex','Patrik'], ['Brad', 'Arnold', 'Jason', 'James']]

In [120]:
data = []
with open("./annual-enterprise-survey-2018-financial-year-provisional-csv.csv", 'r') as file:
    # Начало вашего кода 
    data = list(csv.reader(file, delimiter = ","))
    # Конец вашего кода

col_titles = data[:1]
data = data[1:]

In [121]:
print(col_titles)

[['Year', 'Industry_aggregation_NZSIOC', 'Industry_code_NZSIOC', 'Industry_name_NZSIOC', 'Units', 'Variable_code', 'Variable_name', 'Variable_category', 'Value', 'Industry_code_ANZSIC06']]


### Ожидаемый результат:
```
[['Year', 'Industry_aggregation_NZSIOC', 'Industry_code_NZSIOC', 'Industry_name_NZSIOC', 'Units', 'Variable_code', 'Variable_name', 'Variable_category', 'Value', 'Industry_code_ANZSIC06']]
```

In [44]:
print(data[:5])

[['2018', 'Level 1', '99999', 'All industries', 'Dollars (millions)', 'H01', 'Total income', 'Financial performance', '691859', 'ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O772, S9540, S9601, S9602, and S9603)'], ['2018', 'Level 1', '99999', 'All industries', 'Dollars (millions)', 'H04', 'Sales, government funding, grants and subsidies', 'Financial performance', '605766', 'ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O772, S9540, S9601, S9602, and S9603)'], ['2018', 'Level 1', '99999', 'All industries', 'Dollars (millions)', 'H05', 'Interest, dividends and donations', 'Financial performance', '63509', 'ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O772, S9540, S9601, S9602, and S9603)'], ['2018', 'Level 1', '99999', 'All industries', 'Dollars (millions)', 'H07', 'Non-operating income', 'Financial performance', '22583', 'ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O7

### Ожидаемый результат:
```
[['2018', 'Level 1', '99999', 'All industries', 'Dollars (millions)', 'H01', 'Total income', 'Financial performance', '691859', 'ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O772, S9540, S9601, S9602, and S9603)'], ['2018', 'Level 1', '99999', 'All industries', 'Dollars (millions)', 'H04', 'Sales, government funding, grants and subsidies', 'Financial performance', '605766', 'ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O772, S9540, S9601, S9602, and S9603)'], ['2018', 'Level 1', '99999', 'All industries', 'Dollars (millions)', 'H05', 'Interest, dividends and donations', 'Financial performance', '63509', 'ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O772, S9540, S9601, S9602, and S9603)'], ['2018', 'Level 1', '99999', 'All industries', 'Dollars (millions)', 'H07', 'Non-operating income', 'Financial performance', '22583', 'ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O772, S9540, S9601, S9602, and S9603)'], ['2018', 'Level 1', '99999', 'All industries', 'Dollars (millions)', 'H08', 'Total expenditure', 'Financial performance', '597623', 'ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O772, S9540, S9601, S9602, and S9603)']]
```

In [45]:
print(data[-5:])

[['2013', 'Level 3', 'ZZ11', 'Food product manufacturing', 'Percentage', 'H37', 'Quick ratio', 'Financial ratios', '52', 'ANZSIC06 groups C111, C112, C113, C114, C115, C116, C117, C118, and C119'], ['2013', 'Level 3', 'ZZ11', 'Food product manufacturing', 'Percentage', 'H38', 'Margin on sales of goods for resale', 'Financial ratios', '40', 'ANZSIC06 groups C111, C112, C113, C114, C115, C116, C117, C118, and C119'], ['2013', 'Level 3', 'ZZ11', 'Food product manufacturing', 'Percentage', 'H39', 'Return on equity', 'Financial ratios', '12', 'ANZSIC06 groups C111, C112, C113, C114, C115, C116, C117, C118, and C119'], ['2013', 'Level 3', 'ZZ11', 'Food product manufacturing', 'Percentage', 'H40', 'Return on total assets', 'Financial ratios', '5', 'ANZSIC06 groups C111, C112, C113, C114, C115, C116, C117, C118, and C119'], ['2013', 'Level 3', 'ZZ11', 'Food product manufacturing', 'Percentage', 'H41', 'Liabilities structure', 'Financial ratios', '46', 'ANZSIC06 groups C111, C112, C113, C114, C

### Ожидаемый результат:
```
[['2013', 'Level 3', 'ZZ11', 'Food product manufacturing', 'Percentage', 'H37', 'Quick ratio', 'Financial ratios', '52', 'ANZSIC06 groups C111, C112, C113, C114, C115, C116, C117, C118, and C119'], ['2013', 'Level 3', 'ZZ11', 'Food product manufacturing', 'Percentage', 'H38', 'Margin on sales of goods for resale', 'Financial ratios', '40', 'ANZSIC06 groups C111, C112, C113, C114, C115, C116, C117, C118, and C119'], ['2013', 'Level 3', 'ZZ11', 'Food product manufacturing', 'Percentage', 'H39', 'Return on equity', 'Financial ratios', '12', 'ANZSIC06 groups C111, C112, C113, C114, C115, C116, C117, C118, and C119'], ['2013', 'Level 3', 'ZZ11', 'Food product manufacturing', 'Percentage', 'H40', 'Return on total assets', 'Financial ratios', '5', 'ANZSIC06 groups C111, C112, C113, C114, C115, C116, C117, C118, and C119'], ['2013', 'Level 3', 'ZZ11', 'Food product manufacturing', 'Percentage', 'H41', 'Liabilities structure', 'Financial ratios', '46', 'ANZSIC06 groups C111, C112, C113, C114, C115, C116, C117, C118, and C119']]
```

----
### 1. Подсчитайте, сколько существует различных уровней агрегации отрасли (Industry_aggregation_NZSIOC)

In [61]:
unique_levels = set()

for row in data:
    # Начало вашего кода 
    unique_levels.update(row[1:2])
  
    # Конец вашего кода

In [62]:
print(unique_levels)
print(len(unique_levels))

{'Level 1', 'Level 4', 'Level 3'}
3


### Ожидаемый результат:
```
{'Level 4', 'Level 3', 'Level 1'}
3
```

### 2. Подсчитайте, сколько существует различных отраслей (Industry_name_NZSIOC), и верните список этих уникальных отраслей. 

In [135]:
unique_industries = set()

for row in data:
    # Начало вашего кода 
    unique_industries.update(row[3:4])
    # Конец вашего кода

In [136]:
print(unique_industries)
print(len(unique_industries))

{'Other Store-Based Retailing and Non Store Retailing', 'Tertiary Education', 'Construction Services', 'Electronic and Electrical Equipment Manufacturing', 'Electricity, Gas, Water and Waste Services', 'Adult, Community and Other Education', 'Electricity and Gas Supply', 'Polymer Product and Rubber Product Manufacturing', 'Grocery, Liquor and Tobacco Product Wholesaling', 'Wood Product Manufacturing', 'Real Estate Services', 'Insurance', 'Personal Care, Funeral and Other Personal Services', 'Gambling Activities', 'Machinery and Other Equipment Manufacturing', 'Heritage and Artistic Activities', 'Advertising, Market Research and Management Services', 'Agriculture, Forestry and Fishing', 'Professional, Scientific and Technical Services', 'Veterinary and Other Professional Services', 'Postal and Courier Pick Up and Delivery Services', 'Transport Equipment Manufacturing', 'Mining', 'Non-Residential Building Construction', 'Construction', 'Building Cleaning, Pest Control and Other Support S

### Ожидаемый результат:
```
{'Electricity, Gas, Water and Waste Services', 'Insurance', 'Recreational, Clothing, Footwear and Personal Accessory Retailing', 'Auxiliary Finance and Insurance Services', 'Non-Financial Asset Leasing', 'Education and Training', 'Textile and Leather Manufacturing', 'Commission Based Wholesaling', 'Financial and Insurance Services', 'Supermarket, Grocery Stores and Specialised Food Retailing', 'Information Media and Telecommunications', 'Legal and Accounting Services', 'Hospitals', 'Basic Chemical and Chemical Product Manufacturing', 'Motor Vehicle and Motor Vehicle Parts Wholesaling', 'Transport, Postal and Warehousing', 'Other Goods Wholesaling', 'Machinery Manufacturing', 'Food and Beverage Services', 'Health and General Insurance', 'Sport and Recreation Activities', 'Horticulture and Fruit Growing', 'Travel Agency and Tour Arrangement Services', 'Petroleum and Coal Product Manufacturing', 'Sheep, Beef Cattle and Grain Farming', 'Professional, Scientific, Technical, Administrative and Support Services', 'Non-Residential Building Construction', 'Heritage and Artistic Activities', 'Dairy Cattle Farming', 'Food Product Manufacturing', 'Mining', 'Financial Asset Investing', 'Clothing, Knitted Products and Footwear Manufacturing', 'Basic Chemical and Basic Polymer Manufacturing', 'Wholesale Trade', 'Agriculture, Forestry and Fishing', 'Personal Care, Funeral and Other Personal Services', 'Transport Equipment Manufacturing', 'All industries', 'Rental and Hiring Services (except Real Estate)', 'Property Operators and Real Estate Services', 'Heavy and Civil Engineering Construction', 'Food product manufacturing', 'Construction Services', 'Machinery and Other Equipment Manufacturing', 'Other Services', 'Banking and Financing', 'Health Care and Social Assistance', 'Information Media Services', 'Electronic and Electrical Equipment Manufacturing', 'Gambling Activities', 'Employment and Other Administrative Services', 'Warehousing and Storage Services', 'Retail Trade and Accommodation', 'Finance', 'Water, Sewerage, Drainage and Waste Services', 'Arts and Recreation Services', 'Road Transport', 'Printing', 'Furniture and Other Manufacturing', 'Furniture, Electrical and Hardware Retailing', 'Residential Care Services and Social Assistance', 'Civil, Professional and Other Interest Groups', 'Life Insurance', 'Building Construction', 'Other Manufacturing', 'Accommodation', 'Rail, Water, Air and Other Transport', 'Telecommunications, Internet and Library Services', 'Manufacturing', 'Motor Vehicle and Motor Vehicle Parts and Fuel Retailing', 'Beverage and Tobacco Product Manufacturing', 'Primary Metal and Metal Product Manufacturing', 'Preschool Education', 'Fabricated Metal Product Manufacturing', 'Public Order, Safety and Regulatory Services', 'Wood Product Manufacturing', 'Poultry, Deer and Other Livestock Farming', 'School Education', 'Administrative and Support Services', 'Non-Residential Property Operation', 'Repair and Maintenance', 'Polymer Product and Rubber Product Manufacturing', 'Accommodation and Food Services', 'Pulp, Paper and Converted Paper Product Manufacturing', 'Residential Building Construction', 'Adult, Community and Other Education', 'Non-Metallic Mineral Product Manufacturing', 'Pharmaceutical, Cleaning and Other Chemical Manufacturing', 'Non-Store and Commission Based Retailing', 'Rental, Hiring and Real Estate Services', 'Fertiliser and Pesticide Manufacturing', 'Electricity and Gas Supply', 'Forestry and Logging', 'Furniture Manufacturing', 'Pharmaceutical and Other Store Based Retailing', 'Department Stores', 'Transport Support Services', 'Construction', 'Public order, safety and regulatory services', 'Tertiary Education', 'Medical and Other Health Care Services', 'Postal, Courier, Transport Support, and Warehousing Services', 'Basic Material Wholesaling', 'Computer System Design and Related Services', 'Arts, Recreation and Other Services', 'Postal and Courier Pick Up and Delivery Services', 'Real Estate Services', 'Advertising, Market Research and Management Services', 'Veterinary and Other Professional Services', 'Fishing and Aquaculture', 'Machinery and Equipment Wholesaling', 'Professional, Scientific and Technical Services', 'Grocery, Liquor and Tobacco Product Wholesaling', 'Other Store-Based Retailing and Non Store Retailing', 'Agriculture, Forestry and Fishing Support Services and Hunting', 'Building Cleaning, Pest Control and Other Support Services', 'Textile, Leather, Clothing and Footwear Manufacturing', 'Scientific, Architectural and Engineering Services'}
119
```

### 3. Создайте новые csv-файлы, содержащие данные только за тот же год. Пример: 2018.csv, 2017.csv и т. д.

In [167]:
unique_years = set()

for row in data:
    # Начало вашего кода 
    unique_years.update(row[0:1])
    # Конец вашего кода
print(unique_years)

{'2015', '2013', '2018', '2017', '2014', '2016'}


### Ожидаемый результат:
```
{'2013', '2018', '2017', '2014', '2016', '2015'}
```

In [142]:
for year in unique_years:
    with open("{}.csv".format(year), "w") as ofile:
        # Начало вашего кода 
        writer = csv.writer(ofile)
        writer.writerows('')
        # Конец вашего кода
        print("{}.csv is written".format(year))

2015.csv is written
2013.csv is written
2018.csv is written
2017.csv is written
2014.csv is written
2016.csv is written


### Ожидаемый результат:
```
2013.csv is written
2018.csv is written
2017.csv is written
2014.csv is written
2016.csv is written
2015.csv is written
```

In [140]:
import os

list_of_files = [file for file in os.listdir("./") if file.endswith(".csv")]
print(list_of_files)

['annual-enterprise-survey-2019-financial-year-provisional-csv.csv', 'annual-enterprise-survey-2018-financial-year-provisional-csv.csv']


### Ожидаемый результат:
```
['2018.csv', '2015.csv', '2014.csv', '2016.csv', '2017.csv', '2013.csv', 'annual-enterprise-survey-2018-financial-year-provisional-csv.csv']
```


**Пожалуйста, откройте только что созданные вами CSV-файлы и проверьте, совпадает ли год в этих файлах с именем файла.**

### 4. Дополнительно: просто попробуйте проанализировать больше данных из csv-файла, используя все имеющиеся у вас знания. Пример: сортировка данных по конкретному столбцу.

In [168]:
sum_values = 0

for row in data:
    # Начало вашего кода 
    for i in row[8:9]:
        try:
            sum_values += int(i)
        except:
            continue
    # Конец вашего кода

In [169]:
print(sum_values)

808474992
